server:
  tomcat: 
    uri-encoding: UTF-8 # tomcat的URI编码
#  servlet:
#    context-path: /new-his-service
logging:
  level:
    root: info
    org.apache.ibatis: ERROR
    com.alibaba.druid: ERROR
    com.github.xiaoymin: ERROR
    com.buit: DEBUG
 
spring:
  messages:
    basename: i18n/messages
  datasource:
    name: datasource
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 1
    maxWait: 1000
    minIdle: 2
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 100000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
    removeAbandoned: true
    removeAbandonedTimeout: 30
    logAbandoned: true
#  profiles:
#    include: error # error,abc
  aop:
    auto: true
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    default-property-inclusion: NON_NULL
  servlet:
    multipart.max-file-size: 200MB
    multipart.max-request-size: 200MB
mybatis:
  mapper-locations: classpath*:/com/buit/**/mapper/*Mapper.xml
  type-aliases-package: com.buit
pagehelper:
    reasonable: true  
buit:
  login: 
# errorTime分钟内输入errorNumber次错误密码.锁定用户  
     errorTime: 60
     errorNumber: 10  
