ALTER TABLE `gpo_psdys`
ADD COLUMN `PSDBM` varchar(50) NULL COMMENT '配送点编码' AFTER `YSJGBZ`,
ADD COLUMN `PSDH` varchar(50) NULL COMMENT '配送单号' AFTER `PSDBM`,
ADD COLUMN `YPLX` int(0) NULL COMMENT '药品类型' AFTER `PSDH`,
ADD COLUMN `YXRQ` varchar(50) NULL COMMENT '有效日期' AFTER `YPLX`,
ADD COLUMN `JHDH` varchar(50) NULL COMMENT '计划单号' AFTER `YXRQ`,
ADD COLUMN `XSDDH` varchar(50) NULL COMMENT '销售订单号' AFTER `JHDH`,
ADD COLUMN `DDMXBM` varchar(50) NULL COMMENT '订单明细编码' AFTER `XSDDH`;